apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-management
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: task_management
  ADMIN_USERNAME: cloudeadmin 
  PORT: "5000"
  DB_SSL: "true" # RDS ke liye ture kar na hoga
