apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-external-secret
  namespace: task-management

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: backend-aws-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: task-management/backend/prod
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: task-management/backend/prod
        property: password

    - secretKey: DB_HOST
      remoteRef:
        key: task-management/backend/prod
        property: host

    - secretKey: DB_PORT
      remoteRef:
        key: task-management/backend/prod
        property: port

    - secretKey: DB_NAME
      remoteRef:
        key: task-management/backend/prod
        property: dbname
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: task-management/backend/prod
        property: adminUsername

    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: task-management/backend/prod
        property: adminPassword 
